// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrTCcLjuauJIdQOHjCcl7AOeNxhr2OvF4',
    appId: '1:84109868679:web:36fcbd1aef71d355978222',
    messagingSenderId: '84109868679',
    projectId: 'teahealth-6d55b',
    authDomain: 'teahealth-6d55b.firebaseapp.com',
    storageBucket: 'teahealth-6d55b.firebasestorage.app',
    measurementId: 'G-LTFNR903B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpG04-zKXNF0u3nyp28C7brpTFYpr3atE',
    appId: '1:84109868679:android:89e207a51b561159978222',
    messagingSenderId: '84109868679',
    projectId: 'teahealth-6d55b',
    storageBucket: 'teahealth-6d55b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6vHfHS2D8J9a-uA_xITTzC7vTjAv4Mpg',
    appId: '1:84109868679:ios:7d1dd275cf70a998978222',
    messagingSenderId: '84109868679',
    projectId: 'teahealth-6d55b',
    storageBucket: 'teahealth-6d55b.firebasestorage.app',
    iosClientId: '84109868679-bohamac1kjjqiehshcan60nulm2s1orv.apps.googleusercontent.com',
    iosBundleId: 'com.example.teascanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6vHfHS2D8J9a-uA_xITTzC7vTjAv4Mpg',
    appId: '1:84109868679:ios:7d1dd275cf70a998978222',
    messagingSenderId: '84109868679',
    projectId: 'teahealth-6d55b',
    storageBucket: 'teahealth-6d55b.firebasestorage.app',
    iosClientId: '84109868679-bohamac1kjjqiehshcan60nulm2s1orv.apps.googleusercontent.com',
    iosBundleId: 'com.example.teascanApp',
  );
}
